### ISSUE TITLE
Change and Template is not working for non-string attributes

### ISSUE THREAD

**Issue by rascaraficci** [dojot/mashup#21]
I've tried to map some attributes from a MQTT device to a virtual device using both change and template; it worked for string attributes, but not for the other types.

The used flows are basically:  device --> change/template --> virtual device

**Comment by giovannicuriel** [comment]
Just for the record: the misbehaving component might be perseo. It isn't adding the 'type' attribute in the update message sent to orion, so nothing but strings should be processed (this 'type' check was added to fix a bug where subscriptions created using API v2 weren't being triggered by updates using API v1).

This is a preliminary analysis and needs further investigation.

**Comment by giovannicuriel** [comment]
This is part of dojot/dojot#58

**Comment by giovannicuriel** [comment]
It is only working for attributes with the same name as the original. I'm reopening this.
